repos:
  # Ruff pre-commit hooks
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.7
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]

  # pydoclint pre-commit hooks
  - repo: https://github.com/jsh9/pydoclint
    rev: 0.6.6
    hooks:
      - id: pydoclint
        args: [--style=google, --allow-init-docstring=True]
